import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bookkeeping',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh">
      <body
        className={clsx(
          inter.className,
          'text-sm font-mono text-stone-950 max-w-md m-auto bg-stone-200',
        )}
      >
        {children}
      </body>
    </html>
  )
}
